#
# Module manifest for module 'PSWebGui'
#
# Generated by: JLInF97
#
# Generated on: 01/07/2021
#

@{

# Módulo de script o archivo de módulo binario asociado con este manifiesto.
RootModule = 'PSWebGui.psm1'

# Número de versión de este módulo.
ModuleVersion = '0.13.0'

# PSEditions compatibles
# CompatiblePSEditions = @()

# Id. usado para identificar de forma única este módulo.
GUID = 'efbaa9db-ea59-4170-88db-1e5ef5f11fc9'

# Autor de este módulo.
Author = 'JLInF97'

# Compañía o proveedor de este módulo.
# CompanyName = 'Desconocido'

# Instrucción de copyright de este módulo.
Copyright = '(c) 2021 JLInF97. All rights reserved.'

# Descripción de la funcionalidad proporcionada por este módulo.
Description = 'A fast way to create and display PowerShell graphical interfaces using HTML'

# Versión mínima del motor de Windows PowerShell requerida por este módulo.
PowerShellVersion = '5.0'

# El nombre del host de Windows PowerShell requerido por este módulo.
# PowerShellHostName = ''

# Versión mínima del host de Windows PowerShell requerida por este módulo.
# PowerShellHostVersion = ''

# Versión mínima de Microsoft .NET Framework requerida por este módulo. Este requisito previo únicamente es válido para la edición de escritorio de PowerShell.
# DotNetFrameworkVersion = ''

# Versión mínima de Common Language Runtime (CLR) requerida por este módulo. Este requisito previo únicamente es válido para la edición de escritorio de PowerShell.
# CLRVersion = ''

# Arquitectura de procesador (None, X86, Amd64) que requiere este módulo
# ProcessorArchitecture = ''

# Módulos que se deben importar en el entorno global antes de importar este módulo.
# RequiredModules = @()

# Ensamblados que se deben cargar antes de importar este módulo.
# RequiredAssemblies = @()

# Archivos de script (.ps1) que se ejecutan en el entorno del llamador antes de importar este módulo.
# ScriptsToProcess = @()

# Archivos de tipo (.ps1xml) que se van a cargar al importar este módulo.
# TypesToProcess = @()

# Archivos de formato (.ps1xml) que se van a cargar al importar este módulo.
# FormatsToProcess = @()

# Módulos para importar como módulos anidados del módulo especificado en RootModule/ModuleToProcess
# NestedModules = @()

# Funciones para exportar desde este módulo; para conseguir el mejor rendimiento, no uses caracteres comodines ni elimines la entrada; usa una matriz vacía si no hay funciones que exportar.
FunctionsToExport = "Show-PSWebGUI","Show-PSWebGUIExample","Format-Html","Set-GuiLocation","Write-CredentialForm","Get-CredentialForm","Set-Title","Stop-PsWebGui"

# Cmdlets para exportar desde este módulo; para conseguir el mejor rendimiento, no uses caracteres comodines ni elimines la entrada; usa una matriz vacía si no hay cmdlets que exportar.
CmdletsToExport = @()

# Variables para exportar desde este módulo.
VariablesToExport = '*'

# Alias para exportar desde este módulo; para conseguir el mejor rendimiento, no uses caracteres comodines ni elimines la entrada; usa una matriz vacía si no hay alias que exportar.
AliasesToExport = "Start-PSGUI","Show-PSGUI","Show-WebGUI","Start-WebGUI","FH","SGL"

# Recursos de DSC que se exportarán de este módulo
# DscResourcesToExport = @()

# Lista de todos los módulos empaquetados con este módulo
# ModuleList = @()

# Lista de todos los paquetes con este módulo.
FileList = @("Assets\bootstrap.min.css","Assets\panel.png","Snippets\PSWebGui Basic Structure.snippets.ps1xml","Snippets\PSWebGui Login.snippets.ps1xml")

# Datos privados que se pasan al módulo especificado en RootModule/ModuleToProcess. Pueden contener también una tabla hash PSData con metadatos del módulo adicionales usados por PowerShell.
PrivateData = @{

    PSData = @{

        # Etiquetas aplicadas a este módulo. Ayudan a encontrar el módulo en las galerías en línea.
        Tags = @("gui","ui","html")

        # Dirección URL a la licencia de este módulo.
        LicenseUri = 'https://github.com/JLInF97/PSWebGUI/blob/main/LICENSE'

        # Una dirección URL al sitio web principal de este proyecto.
        ProjectUri = 'https://github.com/JLInF97/PSWebGUI'

        # Una dirección URL a un icono que representa este módulo.
        # IconUri = ''

        # ReleaseNotes de este módulo
        # ReleaseNotes = ''

        # Prerelease string of this module
        Prerelease = 'Beta'

    } # Fin de la tabla hash PSData

} # Fin de la tabla hash PrivateData

# URI de HelpInfo de este módulo
# HelpInfoURI = ''

# Prefijo predeterminado para los comandos exportados desde este módulo. Invalide el prefijo predeterminado mediante Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

