#
# Module manifest for module 'PSWebGui'
#
# Generated by: JLInF97
#
# Generated on: 01/07/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSWebGui.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @("Desktop","Core")

# ID used to uniquely identify this module
GUID = 'efbaa9db-ea59-4170-88db-1e5ef5f11fc9'

# Author of this module.
Author = 'JLInF97'

# Copyright statement for this module
Copyright = '(c) 2021 JLInF97. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A fast way to create and display PowerShell graphical interfaces using HTML'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = "Show-PSWebGUI","Format-Html","Set-GuiLocation","Write-CredentialForm","Get-CredentialForm","Set-Title","Stop-PsWebGui","Hide-PSConsole","Show-PSConsole"

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = "Start-PSGUI","Show-PSGUI","Show-WebGUI","Start-WebGUI","FH","SGL"

# List of all files packaged with this module
FileList = @("Assets\bootstrap.min.css","Snippets\PSWebGui Basic Structure.snippets.ps1xml","Snippets\PSWebGui Login.snippets.ps1xml")

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("gui","ui","html")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/JLInF97/PSWebGUI/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/JLInF97/PSWebGUI'

        # Prerelease string of this module
        # Prerelease = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/JLInF97/PSWebGUI/blob/main/README.md'
}